// Where: Main-process config.
// What: Generates the Python wrapper script that adds app-owned auth in front of WhisperLiveKit.
// Why: Upstream WhisperLiveKit exposes localhost endpoints but does not natively enforce the
//      app-owned token contract required by the local-runtime spec, so the app wraps it at launch time.

import {
  LOCAL_RUNTIME_SERVICE_AUTH_HEADER,
  LOCAL_RUNTIME_SERVICE_AUTH_QUERY_PARAM
} from './local-runtime-service'

export const buildLocalRuntimeServiceHostScript = (): string => `# Generated by Dicta.
# Wraps whisperlivekit.basic_server with app-owned localhost auth enforcement.

import os
from urllib.parse import parse_qs

import uvicorn
from starlette.responses import JSONResponse
from starlette.types import ASGIApp, Receive, Scope, Send

from whisperlivekit.basic_server import app as inner_app, config

SERVICE_TOKEN = os.environ["DICTA_SERVICE_TOKEN"]
AUTH_HEADER_NAME = ${JSON.stringify(LOCAL_RUNTIME_SERVICE_AUTH_HEADER)}.lower().encode("latin-1")
AUTH_QUERY_NAME = ${JSON.stringify(LOCAL_RUNTIME_SERVICE_AUTH_QUERY_PARAM)}


def _extract_header(scope: Scope) -> str | None:
    for key, value in scope.get("headers", []):
        if key == AUTH_HEADER_NAME:
            return value.decode("latin-1")
    return None


def _extract_query(scope: Scope) -> str | None:
    query_bytes = scope.get("query_string", b"")
    if not query_bytes:
        return None
    parsed = parse_qs(query_bytes.decode("utf-8"), keep_blank_values=False)
    values = parsed.get(AUTH_QUERY_NAME)
    if not values:
        return None
    return values[0]


class TokenGuard:
    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        scope_type = scope.get("type")
        if scope_type not in ("http", "websocket"):
            await self.app(scope, receive, send)
            return

        token = _extract_header(scope) or _extract_query(scope)
        if token != SERVICE_TOKEN:
            if scope_type == "websocket":
                await send({"type": "websocket.close", "code": 1008})
                return

            response = JSONResponse({"detail": "Unauthorized"}, status_code=401)
            await response(scope, receive, send)
            return

        await self.app(scope, receive, send)


protected_app = TokenGuard(inner_app)


def main() -> None:
    uvicorn_kwargs = {
        "app": protected_app,
        "host": config.host,
        "port": config.port,
        "reload": False,
        "log_level": "info",
        "lifespan": "on",
    }

    if config.ssl_certfile or config.ssl_keyfile:
        if not (config.ssl_certfile and config.ssl_keyfile):
            raise ValueError("Both --ssl-certfile and --ssl-keyfile must be specified together.")

        uvicorn_kwargs = {
            **uvicorn_kwargs,
            "ssl_certfile": config.ssl_certfile,
            "ssl_keyfile": config.ssl_keyfile,
        }

    if config.forwarded_allow_ips:
        uvicorn_kwargs = {
            **uvicorn_kwargs,
            "forwarded_allow_ips": config.forwarded_allow_ips,
        }

    uvicorn.run(**uvicorn_kwargs)


if __name__ == "__main__":
    main()
`
